package repositories

import (
	"split-udhar-apis/models"
	"split-udhar-apis/utils"

	"gorm.io/gorm"
)

type TransactionRepository struct {
	DB *gorm.DB
}

func NewTransactionRepository(db *gorm.DB) *TransactionRepository {
	return &TransactionRepository{
		DB: db,
	}
}

// WithTx returns a repository bound to tx, so a caller can run several writes
// inside one database transaction and have them roll back together.
func (r *TransactionRepository) WithTx(tx *gorm.DB) *TransactionRepository {
	return &TransactionRepository{DB: tx}
}

func (r *TransactionRepository) Create(transaction *models.Transaction) error {
	return r.DB.Create(transaction).Error
}

func (r *TransactionRepository) Delete(id uint) error {
	return r.DB.Delete(&models.Transaction{}, id).Error
}

func extractTenDigits(mobile string) string {
	return utils.NormalizeMobile(mobile)
}

func (r *TransactionRepository) GetTransactionsBetween(userMobile, otherMobile string) ([]models.Transaction, error) {
	var transactions []models.Transaction
	u10 := extractTenDigits(userMobile)
	o10 := extractTenDigits(otherMobile)

	err := r.DB.
		Select("transactions.*, CASE WHEN transactions.is_archived = true OR `groups`.deleted_at IS NOT NULL THEN true ELSE false END as is_archived").
		Joins("LEFT JOIN `groups` ON transactions.group_id = `groups`.id").
		Where(
			"((transactions.from_mobile = ? OR RIGHT(transactions.from_mobile, 10) = ?) AND (transactions.to_mobile = ? OR RIGHT(transactions.to_mobile, 10) = ?)) OR "+
				"((transactions.from_mobile = ? OR RIGHT(transactions.from_mobile, 10) = ?) AND (transactions.to_mobile = ? OR RIGHT(transactions.to_mobile, 10) = ?))",
			userMobile, u10, otherMobile, o10,
			otherMobile, o10, userMobile, u10,
		).
		Order("transactions.transaction_date DESC").
		Find(&transactions).Error

	return transactions, err
}

func (r *TransactionRepository) GetUserTransactions(userMobile string) ([]models.Transaction, error) {
	var transactions []models.Transaction
	u10 := extractTenDigits(userMobile)

	err := r.DB.
		Select("transactions.*, CASE WHEN transactions.is_archived = true OR `groups`.deleted_at IS NOT NULL THEN true ELSE false END as is_archived").
		Joins("LEFT JOIN `groups` ON transactions.group_id = `groups`.id").
		Where(
			"transactions.from_mobile = ? OR transactions.to_mobile = ? OR RIGHT(transactions.from_mobile, 10) = ? OR RIGHT(transactions.to_mobile, 10) = ?",
			userMobile, userMobile, u10, u10,
		).
		Order("transactions.transaction_date DESC").
		Find(&transactions).Error

	return transactions, err
}

func (r *TransactionRepository) GetByID(id uint) (*models.Transaction, error) {

	var transaction models.Transaction

	err := r.DB.First(&transaction, id).Error
	if err != nil {
		return nil, err
	}

	return &transaction, nil
}

func (r *TransactionRepository) Update(transaction *models.Transaction) error {
	return r.DB.Save(transaction).Error
}

// DeleteByGroupExpense removes the per-member transactions generated by a group
// expense. Used when that expense is edited or deleted, so the personal ledger
// does not keep rows for a split that no longer exists.
func (r *TransactionRepository) DeleteByGroupExpense(expenseID uint) error {
	_ = r.DB.Model(&models.Transaction{}).
		Where("group_expense_id = ?", expenseID).
		Updates(map[string]interface{}{
			"is_deleted": true,
		}).Error
	return r.DB.Where("group_expense_id = ?", expenseID).
		Delete(&models.Transaction{}).Error
}

func (r *TransactionRepository) CreateEditLog(log *models.TransactionEditLog) error {
	return r.DB.Create(log).Error
}

func (r *TransactionRepository) GetEditLogs(transactionID uint) ([]models.TransactionEditLog, error) {
	var logs []models.TransactionEditLog
	err := r.DB.Where("transaction_id = ?", transactionID).Order("created_at DESC").Find(&logs).Error
	return logs, err
}

func (r *TransactionRepository) GetDashboardData(mobile string) (
	given float64,
	received float64,
	count int64,
	err error,
) {
	var transactions []models.Transaction
	u10 := extractTenDigits(mobile)

	err = r.DB.
		Select("transactions.*, CASE WHEN transactions.is_archived = true OR `groups`.deleted_at IS NOT NULL THEN true ELSE false END as is_archived").
		Joins("LEFT JOIN `groups` ON transactions.group_id = `groups`.id").
		Where("`groups`.deleted_at IS NULL OR transactions.group_id IS NULL").
		Where(
			"transactions.from_mobile = ? OR transactions.to_mobile = ? OR RIGHT(transactions.from_mobile, 10) = ? OR RIGHT(transactions.to_mobile, 10) = ?",
			mobile, mobile, u10, u10,
		).
		Find(&transactions).Error

	if err != nil {
		return
	}

	contactBalances := make(map[string]float64)

	for _, transaction := range transactions {
		if transaction.IsDeleted || transaction.IsArchived {
			continue
		}
		// Group split transactions are not merged into peer-to-peer friend balances
		if transaction.GroupID != nil || transaction.ExpenseType == models.ExpenseGroup {
			continue
		}
		count++
		from10 := extractTenDigits(transaction.FromMobile)
		to10 := extractTenDigits(transaction.ToMobile)

		var otherContact string
		if transaction.FromMobile == mobile || from10 == u10 {
			otherContact = to10
			if otherContact == "" {
				otherContact = transaction.ToMobile
			}
			contactBalances[otherContact] += transaction.Amount
		} else if transaction.ToMobile == mobile || to10 == u10 {
			otherContact = from10
			if otherContact == "" {
				otherContact = transaction.FromMobile
			}
			contactBalances[otherContact] -= transaction.Amount
		}
	}

	// A positive net means the contact owes the user, i.e. money still to be
	// received; a negative net is money the user still owes.
	for _, net := range contactBalances {
		if net > 0 {
			received += net
		} else if net < 0 {
			given += -net
		}
	}

	// Add current user's personal financial position from groups (group_members)
	var memberBalances []float64
	_ = r.DB.Model(&models.GroupMember{}).
		Joins("JOIN `groups` ON `groups`.id = group_members.group_id AND `groups`.deleted_at IS NULL").
		Where("(group_members.user_mobile = ? OR RIGHT(group_members.user_mobile, 10) = ?) AND group_members.deleted_at IS NULL", mobile, u10).
		Pluck("group_members.balance", &memberBalances).Error

	for _, bal := range memberBalances {
		if bal > 0 {
			received += bal
		} else if bal < 0 {
			given += -bal
		}
	}

	return
}

func (r *TransactionRepository) GetTransactionsByMobile(
	userMobile string,
	contactMobile string,
) ([]models.Transaction, error) {
	var transactions []models.Transaction
	u10 := extractTenDigits(userMobile)
	c10 := extractTenDigits(contactMobile)

	err := r.DB.
		Select("transactions.*, CASE WHEN transactions.is_archived = true OR `groups`.deleted_at IS NOT NULL THEN true ELSE false END as is_archived").
		Joins("LEFT JOIN `groups` ON transactions.group_id = `groups`.id").
		Where(
			"((transactions.from_mobile = ? OR RIGHT(transactions.from_mobile, 10) = ?) AND (transactions.to_mobile = ? OR RIGHT(transactions.to_mobile, 10) = ?)) OR "+
				"((transactions.from_mobile = ? OR RIGHT(transactions.from_mobile, 10) = ?) AND (transactions.to_mobile = ? OR RIGHT(transactions.to_mobile, 10) = ?))",
			userMobile, u10, contactMobile, c10,
			contactMobile, c10, userMobile, u10,
		).
		Order("transactions.transaction_date DESC").
		Find(&transactions).Error

	return transactions, err
}

func (r *TransactionRepository) Archive(id uint) error {
	return r.DB.Model(&models.Transaction{}).Where("id = ?", id).Update("is_archived", true).Error
}

func (r *TransactionRepository) Unarchive(id uint) error {
	return r.DB.Model(&models.Transaction{}).Where("id = ?", id).Update("is_archived", false).Error
}
